// Auto-generated by the Load Impact converter

import "./libs/shim/core.js";
import "./libs/shim/urijs.js";
import { group } from "k6";

export let options = { maxRedirects: 4, iterations: "100" };

const Request = Symbol.for("request");
postman[Symbol.for("initial")]({
  options,
  collection: {
    Token: ""
  },
  environment: {
    BaseUrl: "http://podinfo.192.168.14.231.xip.io"
  }
});

export default function() {
  group("Basic", function() {
    postman[Request]({
      name: "Get-Version",
      id: "ba4ff9ea-d2ec-49de-a48d-146259829398",
      method: "GET",
      address: "{{BaseUrl}}/version",
      post(response) {
        pm.test("Get-Version: Status code is 200", function() {
          pm.response.to.have.status(200);
        });
      }
    });

    postman[Request]({
      name: "Get-Token",
      id: "6af14511-bc57-46a5-9c86-e3ffecd57126",
      method: "POST",
      address: "{{BaseUrl}}/token",
      post(response) {
        pm.test("Get-Token: Status code is 200", function() {
          pm.response.to.have.status(200);
        });

        pm.test("Get-Token: Set token variable", function() {
          var jsonData = pm.response.json();
          pm.globals.set("Token", jsonData.token);
        });
      }
    });

    postman[Request]({
      name: "Validate-Token",
      id: "c7add553-23a8-48e3-bac3-b7fc14b97692",
      method: "GET",
      address: "{{BaseUrl}}/token/validate",
      post(response) {
        pm.test("Validate-Token: Status code is 200", function() {
          pm.response.to.have.status(200);
        });
      },
      auth(config, Var) {
        config.headers.Authorization = `Bearer ${pm[Var]("Token")}`;
      }
    });
  });

  group("Invasive", function() {
    postman[Request]({
      name: "Store-Content",
      id: "9fc2896e-cb46-417d-9fd3-3a495817137a",
      method: "POST",
      address: "{{BaseUrl}}/store",
      data: '{\n\t"data": "Test content"\n}',
      post(response) {
        pm.test("Store-Content: Status code is 202", function() {
          pm.response.to.have.status(202);
        });
      }
    });
  });
}
